baseURL = 'https://architect.adiendendra.com/'
languageCode = 'en-us'
title = 'Adien'
theme = 'PaperMod'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true 
enableRobotsTXT = true

# --- GLOBAL PARAMETER ---
[outputs]
    home = ["HTML", "RSS", "JSON"]
[params.assets]
    favicon = "/AD_favIcon.png"

[params]
    env = "production"
    mainSections = ["posts", "projects"]
    showFullTextLayout = true
    ShowCodeCopyButtons = true
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowToc= true
    TocOpen= false
    dateFormat = "2 January 2006, 15:04"
    showFullTextInList = false
    displayFullDate = true

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/AdienDendra"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/adiendendra"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:adien.dendra@gmail.com"

[markup.goldmark.renderer]
  unsafe = true
  
# --- LANGUAGE CONFIGURATION ---
[languages]
    # --- ENGLISH (DEFAULT) ---
    [languages.en]
        languageName = "En"
        contentDir = "content.en"
        weight = 1
        [languages.en.params]
            title = "Adien"
            description = "Creature TD & Solution Architect"
            [languages.en.params.profileMode]
                enabled = true
                title = " "
                subtitle = "Creature TD @ ILM | Aspiring Cloud Architect | Sydney"
                imageUrl = "https://github.com/AdienDendra.png"
                imageWidth = 120
                imageHeight = 120
                [[languages.en.params.profileMode.buttons]]
                    name = "Projects"
                    url = "/en/projects/"

        # HEADER MENU (English)
        [[languages.en.menu.main]]
            name = "Projects"
            url = "/en/projects/"
            weight = 1
        [[languages.en.menu.main]]
            name = "Blog"
            url = "/en/posts/"
            weight = 5
        [[languages.en.menu.main]]
            name = "Archive"
            url = "/en/archives/"
            weight = 10
        [[languages.en.menu.main]]
            identifier = "search"
            name = "⌕"
            url = "/en/search/"
            weight = 15

    # --- BAHASA INDONESIA ---
    [languages.id]
        languageName = "Id"
        contentDir = "content.id"
        weight = 2
        [languages.id.params]
            title = "Adien"
            description = "Creature TD & Solution Architect"
            [languages.id.params.profileMode]
                enabled = true
                title = " "
                subtitle = "Creature TD @ ILM | Calon Cloud Architect | Sydney"
                imageUrl = "https://github.com/AdienDendra.png"
                imageWidth = 120
                imageHeight = 120
                # pakai /id/ agar tidak balik ke English
                [[languages.id.params.profileMode.buttons]]
                    name = "Proyek"
                    url = "/id/projects/"

       [[languages.id.menu.main]]
            name = "Proyek"
            url = "/id/projects/"
            weight = 1
        [[languages.id.menu.main]]
            name = "Blog"
            url = "/id/posts/"
            weight = 5
        [[languages.id.menu.main]]
            name = "Arsip"
            url = "/id/archives/"
            weight = 10
        [[languages.id.menu.main]]
            identifier = "search"
            name = "⌕"            
            url = "/id/search/"
            weight = 15
